apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- deployment.yaml
- ingress.yaml
namespace: staging
images:
  - name: toleksa/argo-combined-app
    newTag: "21fa0ce62d35b214039c55f8575c3af69dbafe57"
